global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "microservice"
    static_configs:
      - targets: ["host.docker.internal:5000"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]